addict==2.4.0
anyio==3.3.4
argcomplete==1.12.3
argon2-cffi==21.1.0
attrs==21.2.0
Babel==2.9.1
backcall==0.2.0
bleach==4.1.0
cached-property==1.5.2
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.7
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1632508026186/work
# Editable install with no version control (custma==0.0.1)
-e /data/lab-wangzihao/Differentiable_SpeckleNet/CuStereoMatching-dev
cycler==0.10.0
cytoolz==0.11.0
dask==1.1.4
debugpy==1.5.1
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
defusedxml==0.7.1
deprecation==2.1.0
distlib==0.3.4
entrypoints==0.3
freetype-py==2.3.0
h5py==3.5.0
idna==3.3
imageio @ file:///tmp/build/80754af9/imageio_1617700267927/work
importlib-metadata==4.8.1
ipdb==0.13.9
ipykernel==6.4.2
ipython==7.28.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
jedi==0.18.0
Jinja2==3.0.2
joblib==1.1.0
json5==0.9.6
jsonschema==4.1.2
jupyter-client==7.0.6
jupyter-core==4.8.1
jupyter-packaging==0.11.0
jupyter-server==1.11.1
jupyterlab==3.2.1
jupyterlab-pygments==0.1.2
jupyterlab-server==2.8.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.2
MarkupSafe==2.0.1
matplotlib==3.4.3
matplotlib-inline==0.1.3
mistune==0.8.4
mkl-fft==1.3.1
mkl-random @ file:///tmp/build/80754af9/mkl_random_1626179032232/work
mkl-service==2.4.0
nbclassic==0.3.3
nbclient==0.5.4
nbconvert==6.2.0
nbformat==5.1.3
nest-asyncio==1.5.1
networkx==2.2
notebook==6.4.5
numpy==1.21.3
olefile==0.46
open3d==0.15.2
open3d-python==0.7.0.0
opencv-python==4.5.2.54
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas==1.3.4
pandocfilters==1.5.0
parso==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.4.0
pip-custom-platform==0.2.0
plyfile==0.7.4
prometheus-client==0.11.0
prompt-toolkit==3.0.21
ptyprocess==0.7.0
pycparser==2.20
pyglet==1.5.26
Pygments==2.10.0
PyOpenGL==3.1.0
pyparsing @ file:///tmp/build/80754af9/pyparsing_1635766073266/work
pyquaternion==0.9.9
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.3
PyWavelets @ file:///tmp/build/80754af9/pywavelets_1648727874099/work
PyYAML==6.0
pyzmq==22.3.0
redner==0.4.28
requests==2.26.0
requests-unixsocket==0.2.0
scikit-image @ file:///tmp/build/80754af9/scikit-image_1648196043170/work
scikit-learn==1.0
scipy @ file:///tmp/build/80754af9/scipy_1630606797510/work
Send2Trash==1.8.0
six @ file:///tmp/build/80754af9/six_1623709665295/work
sklearn==0.0
sniffio==1.2.0
terminado==0.12.1
testpath==0.5.0
threadpoolctl==3.0.0
tifffile==2020.10.1
toml==0.10.2
tomlkit==0.7.2
toolz @ file:///tmp/build/80754af9/toolz_1636545406491/work
torch==1.7.1
torchaudio==0.7.0a0+a853dff
torchvision==0.8.2
tornado==6.1
tqdm==4.62.3
traitlets==5.1.0
trimesh==3.12.3
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1631814937681/work
urllib3==1.26.7
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.1
widgetsnbextension==3.5.1
zipp==3.6.0
